apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: my-app-namespace
type: Opaque
data:
  spring.datasource.username: "cG9zdGdyZXM="  # postgres
  spring.datasource.password: "aGFsYW1hZHJpZA=="  # halamadrid
